# 2. Работа с SQLite в pandas

Используя библиотеку pandas, напишите скрипт, который

- Загружает файл SQLite с названием database.sqlite
- На его основе создает объект Dataframe
- Выполняет 3 действия с датафреймом:
    - оставляет только колонку airline
    - удаляет дубликаты значений
    - сортирует значения по алфавит
- Сохраняет полученный датафрейм в новый файл с именем airline.sqlite

Источник данных - https://www.kaggle.com/datasets/crowdflower/twitter-airline-sentiment

In [2]:
import pandas as pd

In [3]:
import sqlite3

In [4]:
database = pd.read_sql_query("SELECT * FROM Tweets", con=sqlite3.connect("data/task2/database.sqlite"))

In [5]:
database.head()

,tweet_id,airline_sentiment,airline_sentiment_confidence,negativereason,negativereason_confidence,airline,airline_sentiment_gold,name,negativereason_gold,retweet_count,text,tweet_coord,tweet_created,tweet_location,user_timezone
0,567588278875213824,neutral,1.0,,,Delta,,JetBlueNews,,0,@JetBlue's new CEO seeks the right balance to ...,,2015-02-16 23:36:05 -0800,USA,Sydney
1,567590027375702016,negative,1.0,Can't Tell,0.6503,Delta,,nesi_1992,,0,@JetBlue is REALLY getting on my nerves !! 😡😡 ...,,2015-02-16 23:43:02 -0800,undecided,Pacific Time (US & Canada)
2,567591480085463040,negative,1.0,Late Flight,0.346,United,,CPoutloud,,0,@united yes. We waited in line for almost an h...,,2015-02-16 23:48:48 -0800,"Washington, DC",
3,567592368451248130,negative,1.0,Late Flight,1,United,,brenduch,,0,@united the we got into the gate at IAH on tim...,,2015-02-16 23:52:20 -0800,,Buenos Aires
4,567594449874587648,negative,1.0,Customer Service Issue,0.3451,Southwest,,VahidESQ,,0,@SouthwestAir its cool that my bags take a bit...,,2015-02-17 00:00:36 -0800,"Los Angeles, CA",Pacific Time (US & Canada)

In [6]:
database = database[["airline"]]

In [7]:
database

          airline
0           Delta
1           Delta
2          United
3          United
4       Southwest
...           ...
14480       Delta
14481  US Airways
14482       Delta
14483  US Airways
14484  US Airways

[14485 rows x 1 columns]

In [8]:
database.drop_duplicates(inplace=True)  # Удаляем дубликаты

In [9]:
database

             airline
0              Delta
2             United
4          Southwest
14        US Airways
94    Virgin America
2674        American

In [10]:
database.sort_values("airline", inplace=True)

In [11]:
database

             airline
2674        American
0              Delta
4          Southwest
14        US Airways
2             United
94    Virgin America

In [12]:
database.to_sql("airline", con=sqlite3.connect("data/task2/airline.sqlite"))

6