# 1. Работа с файлами CSV в pandas

Используя библиотеку pandas, напишите скрипт, в котором

- Загрузить файл CSV с названием vgsales.csv
- На его основе создать объект Dataframe
- Привести Year к числовому типу
- Удалить строки с пропущенным Year
- Проверить типы столбцов продаж (float)
- Создать столбец Total_Regional_Sales = NA + EU + JP + Other
- Создать столбец Sales_Diff = Global_Sales - Total_Regional_Sales
- Сформировать итоговый DataFrame с колонками:
    - Name, Platform, Year, Genre, Publisher, Global_Sales, Total_Regional_Sales, Sales_Diff
- Выбрать строки, где Sales_Diff != 0
- Отсортировать по убыванию Sales_Diff
- Сохранить полученный датафрейм в новый файл с именем vgsales_cleaned_analysis.csv без сохранения индексов

Файл CSV представлен по ссылке - https://www.kaggle.com/datasets/gregorut/videogamesales

In [19]:
import pandas as pd

In [20]:
vgsales = pd.read_csv("data/task1/vgsales.csv")  # Читаем и создаём фрейм данных из файла vgsales.csv

In [21]:
vgsales.info()  # Проверяем типы данных

<class 'pandas.DataFrame'>
RangeIndex: 16598 entries, 0 to 16597
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Rank          16598 non-null  int64
 1   Name          16598 non-null  str
 2   Platform      16598 non-null  str
 3   Year          16327 non-null  float64
 4   Genre         16598 non-null  str
 5   Publisher     16540 non-null  str
 6   NA_Sales      16598 non-null  float64
 7   EU_Sales      16598 non-null  float64
 8   JP_Sales      16598 non-null  float64
 9   Other_Sales   16598 non-null  float64
 10  Global_Sales  16598 non-null  float64
dtypes: float64(6), int64(1), str(4)
memory usage: 2.1 MB

In [22]:
vgsales[vgsales["Year"].isna()]  # Вывод строк, где в столбце "Year" пусто

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
179,180,Madden NFL 2004,PS2,NaN,Sports,Electronic Arts,4.26,0.26,0.01,0.71,5.23
377,378,FIFA Soccer 2004,PS2,NaN,Sports,Electronic Arts,0.59,2.36,0.04,0.51,3.49
431,432,LEGO Batman: The Videogame,Wii,NaN,Action,Warner Bros. Interactive Entertainment,1.86,1.02,0.00,0.29,3.17
470,471,wwe Smackdown vs. Raw 2006,PS2,NaN,Fighting,NaN,1.57,1.02,0.00,0.41,3.00
607,608,Space Invaders,2600,NaN,Shooter,Atari,2.36,0.14,0.00,0.03,2.53
...,...,...,...,...,...,...,...,...,...,...,...
16307,16310,Freaky Flyers,GC,NaN,Racing,Unknown,0.01,0.00,0.00,0.00,0.01
16327,16330,Inversion,PC,NaN,Shooter,Namco Bandai Games,0.01,0.00,0.00,0.00,0.01
16366,16369,Hakuouki: Shinsengumi Kitan,PS3,NaN,Adventure,Unknown,0.01,0.00,0.00,0.00,0.01
16427,16430,Virtua Quest,GC,NaN,Role-Playing,Unknown,0.01,0.00,0.00,0.00,0.01
16493,16496,The Smurfs,3DS,NaN,Action,Unknown,0.00,0.01,0.00,0.00,0.01

In [23]:
vgsales["Year"] = pd.to_numeric(vgsales["Year"])  # Приводим столбец "Year" к числовому типу данных

In [24]:
vgsales.info()  # Проверяем типы данных

<class 'pandas.DataFrame'>
RangeIndex: 16598 entries, 0 to 16597
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Rank          16598 non-null  int64
 1   Name          16598 non-null  str
 2   Platform      16598 non-null  str
 3   Year          16327 non-null  float64
 4   Genre         16598 non-null  str
 5   Publisher     16540 non-null  str
 6   NA_Sales      16598 non-null  float64
 7   EU_Sales      16598 non-null  float64
 8   JP_Sales      16598 non-null  float64
 9   Other_Sales   16598 non-null  float64
 10  Global_Sales  16598 non-null  float64
dtypes: float64(6), int64(1), str(4)
memory usage: 2.1 MB

In [25]:
vgsales.dropna(subset=["Year"], inplace=True)  # Удаляем строки, где в столбце "Year" пусто

In [26]:
vgsales[vgsales["Year"].isna()]  # Проверяем, что строки с пустыми значениями в столбце "Year" удалены

Empty DataFrame
Columns: [Rank, Name, Platform, Year, Genre, Publisher, NA_Sales, EU_Sales, JP_Sales, Other_Sales, Global_Sales]
Index: []

In [27]:
vgsales["Total_Regional_Sales"] = vgsales["NA_Sales"] + vgsales["EU_Sales"] + vgsales["JP_Sales"] + vgsales["Other_Sales"]  # Создаём новый столбец "Total_Regional_Sales"

In [28]:
vgsales[abs(vgsales["Global_Sales"] - vgsales["Total_Regional_Sales"]) > 1]  # Выводим строки, где разница между "Global_Sales" и "Total_Regional_Sales" больше 1

Empty DataFrame
Columns: [Rank, Name, Platform, Year, Genre, Publisher, NA_Sales, EU_Sales, JP_Sales, Other_Sales, Global_Sales, Total_Regional_Sales]
Index: []

In [29]:
vgsales["Sales_Diff"] = vgsales["Global_Sales"] - vgsales["Total_Regional_Sales"]  # Создаём новый столбец "Sales_Diff"

In [30]:
vgsales.head()

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales,Total_Regional_Sales,Sales_Diff
0,1,Wii Sports,Wii,2006.0,Sports,Nintendo,41.49,29.02,3.77,8.46,82.74,82.74,-1.421085e-14
1,2,Super Mario Bros.,NES,1985.0,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24,40.24,0.000000e+00
2,3,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.85,12.88,3.79,3.31,35.82,35.83,-1.000000e-02
3,4,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,15.75,11.01,3.28,2.96,33.00,33.00,0.000000e+00
4,5,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37,31.38,-1.000000e-02

In [31]:
vgsales = vgsales[["Name", "Platform", "Year", "Genre", "Publisher", "Global_Sales", "Total_Regional_Sales", "Sales_Diff"]]

In [32]:
vgsales

,Name,Platform,Year,Genre,Publisher,Global_Sales,Total_Regional_Sales,Sales_Diff
0,Wii Sports,Wii,2006.0,Sports,Nintendo,82.74,82.74,-1.421085e-14
1,Super Mario Bros.,NES,1985.0,Platform,Nintendo,40.24,40.24,0.000000e+00
2,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,35.82,35.83,-1.000000e-02
3,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,33.00,33.00,0.000000e+00
4,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,Nintendo,31.37,31.38,-1.000000e-02
...,...,...,...,...,...,...,...,...
16593,Woody Woodpecker in Crazy Castle 5,GBA,2002.0,Platform,Kemco,0.01,0.01,0.000000e+00
16594,Men in Black II: Alien Escape,GC,2003.0,Shooter,Infogrames,0.01,0.01,0.000000e+00
16595,SCORE International Baja 1000: The Official Game,PS2,2008.0,Racing,Activision,0.01,0.00,1.000000e-02
16596,Know How 2,DS,2010.0,Puzzle,7G//AMES,0.01,0.01,0.000000e+00
16597,Spirits & Spells,GBA,2003.0,Platform,Wanadoo,0.01,0.01,0.000000e+00

In [33]:
vgsales = vgsales[vgsales["Sales_Diff"] != 0]  # Удаляем строки, где разница между "Global_Sales" и "Total_Regional_Sales" равна 0

In [34]:
vgsales[vgsales["Sales_Diff"] == 0]  # Проверяем, что строки с разницей между "Global_Sales" и "Total_Regional_Sales", равной 0, удалены

Empty DataFrame
Columns: [Name, Platform, Year, Genre, Publisher, Global_Sales, Total_Regional_Sales, Sales_Diff]
Index: []

In [35]:
vgsales.sort_values("Sales_Diff", ascending=False, inplace=True)  # Сортируем по столбцу "Sales_Diff" в порядке убывания

In [36]:
vgsales.to_csv("data/task1/vgsales_cleaned_analysis.csv", index=False)  # Сохраняем очищенный и обработанный фрейм данных в новый CSV файл