# Pandas Tutorial

video from: **Complete Python Pandas Data Science Tutorial! (2025 Updated Edition)** - https://www.youtube.com/watch?v=2uvysYbKdjM

In [28]:
import pandas as pd

In [ ]:
# Названия колонок часто есть по умолчанию во входных файлах
# Названия строк можно тоже не давать. По умолчанию все: 0, 1, 2, ...
df = pd.DataFrame([[1, 2, 3], [4, 5, 6], [7, 8, 9]], columns=["A", "B", "C"], index=["x", "y", "z"])

df.head()  # Вывод первых 5 записей

   A  B  C
x  1  2  3
y  4  5  6
z  7  8  9

In [30]:
df.head(2)  # Вывод первых 2 записей

   A  B  C
x  1  2  3
y  4  5  6

In [31]:
df.tail(2)  # Вывод последних 2 записей

   A  B  C
y  4  5  6
z  7  8  9

In [32]:
df  # Вывод всего фрейма

   A  B  C
x  1  2  3
y  4  5  6
z  7  8  9

In [33]:
df.columns  # Названия колонок; можно с .to_list()

Index(['A', 'B', 'C'], dtype='str')

In [34]:
df.index  # Названия строк

Index(['x', 'y', 'z'], dtype='str')

In [35]:
df.index.to_list()  # Названия строк в виде списка

['x', 'y', 'z']

In [36]:
df.info()

<class 'pandas.DataFrame'>
Index: 3 entries, x to z
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       3 non-null      int64
 1   B       3 non-null      int64
 2   C       3 non-null      int64
dtypes: int64(3)
memory usage: 96.0+ bytes

In [ ]:
df.describe()  # Информация для каждого столбца
# Количество элементов
# Среднее
# Стандартное отклонение
# Минимальное значение
# и т.д.

         A    B    C
count  3.0  3.0  3.0
mean   4.0  5.0  6.0
std    3.0  3.0  3.0
min    1.0  2.0  3.0
25%    2.5  3.5  4.5
50%    4.0  5.0  6.0
75%    5.5  6.5  7.5
max    7.0  8.0  9.0

In [ ]:
df.nunique()  # Количество уникальных элементов в столбцах

A    3
B    3
C    3
dtype: int64

In [ ]:
df["A"].unique()  # Уникальные значения для конкретного столбца

array([1, 4, 7])

In [47]:
df.shape  # Форма фрейма: (строк, столбцов)

(3, 3)

In [ ]:
df.size  # Количество элементов во фрейме

9