In [1]:
import pandas as pd

## Задача 1

Напишите функцию, которая создает объект Series из списка натуральных чисел и пользовательскими индексами, состоящими из всех букв латинского алфавита, используя библиотеку pandas.

Функция не должна принимать аргументы. Результат операции выведите с помощью return.

In [2]:
from string import ascii_lowercase


def numbers_series():
    data = pd.Series()
    for numb, symb in enumerate(ascii_lowercase):
        data[symb] = numb + 1
    return data


print(numbers_series())

a     1
b     2
c     3
d     4
e     5
f     6
g     7
h     8
i     9
j    10
k    11
l    12
m    13
n    14
o    15
p    16
q    17
r    18
s    19
t    20
u    21
v    22
w    23
x    24
y    25
z    26
dtype: int64

## Задача 2

Напишите функцию, которая принимает на вход словарь, на его основе создает объект Dataframe и возвращает первые три записи из него, используя библиотеку pandas.

Функция должна принимать один аргумент. Результат операции выведите с помощью return.

Аргумент - словарь.

In [3]:
d = {
    "fruits":
    [
        "apple", "banana", "orange", "grape", "pear",
        "kiwi", "strawberry", "blueberry", "mango", "pineapple",
        "watermelon", "peach", "plum", "cherry", "lemon"
    ],
    "colors":
    [
        "red", "blue", "green", "yellow", "purple",
        "orange", "pink", "brown", "black", "white",
        "gray", "cyan", "magenta", "lime", "navy"
    ],
    "movies":
    [
        "Inception", "Titanic", "Avatar", "The Matrix", "The Godfather",
        "Pulp Fiction", "The Shawshank Redemption", "Forrest Gump", "Gladiator", "Interstellar",
        "The Dark Knight", "Fight Club", "Jurassic Park", "The Lion King", "Schindler's List"
    ],
    "animals":
    [
        "dog", "cat", "elephant", "tiger", "lion",
        "giraffe", "bear", "zebra", "kangaroo", "panda",
        "fox", "wolf", "rabbit", "squirrel", "deer"
    ],
    "professions":
    [
        "doctor", "teacher", "engineer", "artist", "nurse",
        "scientist", "musician", "writer", "chef", "mechanic",
        "programmer", "architect", "journalist", "farmer", "electrician"
    ]
}

In [4]:
def three_dict(d):
    d = pd.DataFrame(d)
    return d.loc[:2]


print(three_dict(d))

   fruits colors     movies   animals professions
0   apple    red  Inception       dog      doctor
1  banana   blue    Titanic       cat     teacher
2  orange  green     Avatar  elephant    engineer

## Задача 3

Используя библиотеку pandas, напишите скрипт, который

- загружает файл CSV с названием user_behavior_dataset.csv
- на его основе создает объект Dataframe
- оставляет в датафрейме только те записи, в которых значение поля age равно 19
- сохраняет полученный датафрейм в новый файл с именем age_19.csv без сохранения индексов

Источник данных - https://www.kaggle.com/datasets/valakhorasani/mobile-device-usage-and-user-behavior-dataset

In [5]:
user_behavior_dataset = pd.read_csv("data/user_behavior_dataset.csv")

In [6]:
user_behavior_dataset = user_behavior_dataset[user_behavior_dataset["Age"] == 19]

In [7]:
user_behavior_dataset

,User ID,Device Model,Operating System,App Usage Time (min/day),Screen On Time (hours/day),Battery Drain (mAh/day),Number of Apps Installed,Data Usage (MB/day),Age,Gender,User Behavior Class
29,30,Samsung Galaxy S21,Android,412,6.2,1899,78,1384,19,Female,4
83,84,Xiaomi Mi 11,Android,39,1.8,368,11,105,19,Male,1
101,102,OnePlus 9,Android,183,4.1,1210,45,738,19,Male,3
111,112,Xiaomi Mi 11,Android,488,8.6,2447,84,2344,19,Male,5
198,199,OnePlus 9,Android,80,1.6,549,14,197,19,Male,1
235,236,Xiaomi Mi 11,Android,37,1.4,369,18,295,19,Female,1
237,238,OnePlus 9,Android,425,6.9,2142,66,1130,19,Female,4
247,248,Google Pixel 5,Android,314,6.2,2205,63,1066,19,Male,4
257,258,Xiaomi Mi 11,Android,272,5.0,1655,45,686,19,Female,3
304,305,iPhone 12,iOS,155,2.9,1117,22,322,19,Female,2
554,555,iPhone 12,iOS,387,6.6,2168,61,1246,19,Female,4
582,583,iPhone 12,iOS,191,5.7,1414,53,991,19,Female,3

In [ ]:
user_behavior_dataset.to_csv("data/age_19.csv", index=False)

## Задача 4

Используя библиотеку pandas, напишите скрипт, который

- загружает файл SQLite с названием european_database.sqlite
- на его основе создает объект Dataframe
- оставляет в датафрейме одну колонку с удалением дубликатов - 'country'
- сохраняет полученный датафрейм в новый файл с именем new_database.sqlite

Источник данных - https://www.kaggle.com/datasets/groleo/european-football-database

In [9]:
import sqlite3

In [10]:
database = pd.read_sql_query("SELECT * FROM divisions", con=sqlite3.connect("data/european_database.sqlite"))

In [11]:
df_unique = database[["country"]].drop_duplicates()

In [12]:
df_unique

        country
0       Belgium
1   Deutschland
3       England
8        France
10       Greece
11        Italy
13  Netherlands
14     Portugal
15     Scotland
18        Spain
20       Turkey

In [44]:
df_unique.to_sql("countries", con=sqlite3.connect("data/new_database.sqlite"), index=False, if_exists="replace")  # если уже существует - перезаписать

11

## Задача 5

Используя библиотеку pandas, напишите скрипт, который

- загружает файл JSON с названием games_metadata.json
- на его основе создает объект Dataframe
- выполняет фильтрацию игр с тегами Strategy и RTS
- создает сводную таблицу с подсчетом количества игр по жанрам
- сортирует по количеству игр
- сохраняет полученный датафрейм в новый файл с именем games_strategy_rts.json

Источник данных - https://www.kaggle.com/datasets/antonkozyriev/game-recommendations-on-steam

In [22]:
games_metadata = pd.read_json("data/games_metadata.json", orient="records", lines=True)

In [23]:
games_metadata.head()

,app_id,description,tags
0,13500,Enter the dark underworld of Prince of Persia ...,"[Action, Adventure, Parkour, Third Person, Gre..."
1,22364,,[Action]
2,113020,Monaco: What's Yours Is Mine is a single playe...,"[Co-op, Stealth, Indie, Heist, Local Co-Op, St..."
3,226560,Escape Dead Island is a Survival-Mystery adven...,"[Zombies, Adventure, Survival, Action, Third P..."
4,249050,Dungeon of the Endless is a Rogue-Like Dungeon...,"[Roguelike, Strategy, Tower Defense, Pixel Gra..."

In [24]:
games_metadata.info()

<class 'pandas.DataFrame'>
RangeIndex: 50872 entries, 0 to 50871
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   app_id       50872 non-null  int64
 1   description  50872 non-null  str
 2   tags         50872 non-null  object
dtypes: int64(1), object(1), str(1)
memory usage: 9.1+ MB

In [28]:
games_metadata["tags"]

0        [Action, Adventure, Parkour, Third Person, Gre...
1                                                 [Action]
2        [Co-op, Stealth, Indie, Heist, Local Co-Op, St...
3        [Zombies, Adventure, Survival, Action, Third P...
4        [Roguelike, Strategy, Tower Defense, Pixel Gra...
                               ...
50867                                                   []
50868                                                   []
50869                                                   []
50870    [Early Access, FPS, Action, Retro, First-Perso...
50871                                                   []
Name: tags, Length: 50872, dtype: object

In [29]:
games_metadata = games_metadata[games_metadata['tags'].apply(lambda tags: "Strategy" and "RTS" in tags)]

In [30]:
games_metadata

,app_id,description,tags
7,271850,,"[Strategy, Simulation, Action, RTS, World War II]"
12,22130,Includes Hearts of Iron II plus the two expans...,"[Strategy, Grand Strategy, World War II, Histo..."
28,437000,The ultimate melee action [GUILTY GEAR 2 -OVER...,"[Action, Fighting, Anime, RTS, Story Rich, Gre..."
49,254820,"The year is 2419. War has devastated Earth, an...","[Strategy, RTS, Real Time Tactics, Sci-fi, Cla..."
56,342310,As civil crisis deepens and inequality tears t...,"[Strategy, Simulation, Indie, Pixel Graphics, ..."
...,...,...,...
50743,2411910,"""miniBONG"" is a lightweight rogue-like game th...","[Casual, Idler, Character Customization, Loot,..."
50747,2232650,The best elements of Real-Time Strategy (RTS) ...,"[Early Access, Exploration, Time Management, W..."
50796,2392520,The latest edition of the ultrarealistic world...,"[Simulation, Strategy, RTS, Political Sim, Rea..."
50803,2296550,From the developers of Element TD 2 comes a Ma...,"[Tower Defense, Real Time Tactics, Strategy, R..."
50814,2180550,"Eva, the half-dragon, half-human princess. Pfe...","[Sexual Content, Nudity, JRPG, NSFW, Action-Ad..."

In [27]:
results = games_metadata.explode("tags")
results

,app_id,description,tags
0,13500,Enter the dark underworld of Prince of Persia ...,Action
0,13500,Enter the dark underworld of Prince of Persia ...,Adventure
0,13500,Enter the dark underworld of Prince of Persia ...,Parkour
0,13500,Enter the dark underworld of Prince of Persia ...,Third Person
0,13500,Enter the dark underworld of Prince of Persia ...,Great Soundtrack
...,...,...,...
50870,2272250,Embark on a journey into the darkest nightmare...,Psychedelic
50870,2272250,Embark on a journey into the darkest nightmare...,Gore
50870,2272250,Embark on a journey into the darkest nightmare...,Adventure
50870,2272250,Embark on a journey into the darkest nightmare...,Character Customization
50871,2488510,,NaN

In [31]:
pivot = games_metadata.explode("tags").pivot_table(index="tags", values="app_id", aggfunc="count")

In [32]:
pivot

              app_id
tags
1980s              5
1990's            20
2.5D              24
2D               264
2D Fighter         6
...              ...
World War I       15
World War II     127
Wrestling          1
Zombies           42
eSports           21

[372 rows x 1 columns]

In [40]:
pivot.sort_values("app_id", inplace=True)

In [41]:
pivot

                       app_id
tags
Wrestling                   1
Word Game                   1
Conspiracy                  1
Character Action Game       1
Souls-like                  1
...                       ...
Simulation                502
Indie                     526
Singleplayer              740
Strategy                 1191
RTS                      1236

[372 rows x 1 columns]

In [42]:
pivot.to_json("data/games_strategy_rts.json")